name: Deploy to Production

on:
  push:
    branches:
      - main  # Ganti dengan branch yang ingin Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Tambahkan kunci SSH ke Secrets di GitHub

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Run Envoy Deployment
        run: |
          composer global require laravel/envoy
          ~/.composer/vendor/bin/envoy run deploy --commit="${{ github.sha }}"
